# Generated by Django 2.2.1 on 2019-05-12 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('num_teams', models.IntegerField()),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fantasy_league',
            },
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('fantasy_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.FantasyLeague')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fantasy_team',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('player_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('nba_team_id', models.IntegerField(null=True)),
                ('nba_team_abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gp', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fgm', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fga', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fg_pct', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fg3m', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fg3a', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fg3_pct', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ftm', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fta', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ft_pct', models.DecimalField(decimal_places=3, max_digits=4)),
                ('oreb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dreb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reb', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ast', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tov', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stl', models.DecimalField(decimal_places=1, max_digits=3)),
                ('blk', models.DecimalField(decimal_places=1, max_digits=3)),
                ('blka', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pf', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pfd', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pts', models.DecimalField(decimal_places=1, max_digits=3)),
                ('plus_minus', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerFantasyTeamXRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.FantasyLeague')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.FantasyTeam')),
            ],
            options={
                'db_table': 'player_fantasy_team_xref',
            },
        ),
    ]
