# Generated by Django 2.2.1 on 2019-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
