# Generated by Django 2.2.1 on 2019-05-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_sports', '0002_fantasyleague_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_sports.FantasyTeam')),
            ],
            options={
                'db_table': 'draft_pick',
            },
        ),
    ]
